name: movie_app
description: "A Flutter project to download movies."
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6  # Include Cupertino Icons
  carousel_slider: ^4.0.0
  http: ^0.13.4
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  html: ^0.15.0
  url_launcher: ^6.3.1
  #url_launcher: ^6.3.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # Linting package for good coding practices

flutter:
  uses-material-design: true  # Enable Material Design
  assets:
    - assets/  # Ensure you have this directory with assets in your project
